"""update material_list_item_quoted fields

Revision ID: cbac99a94c4d
Revises: 2e8937518893
Create Date: 2025-08-12 15:25:54.394999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbac99a94c4d'
down_revision: Union[str, Sequence[str], None] = '2e8937518893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_list_item_quoted', sa.Column('comment', sa.String(), nullable=True))
    op.alter_column('material_list_item_quoted', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('material_list_item_quoted', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('material_list_item_quoted', 'comment')
    # ### end Alembic commands ###
