"""added original_item_id to MaterialQuoted

Revision ID: d11259523e06
Revises: ee415be68cd3
Create Date: 2025-08-13 12:12:12.151337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd11259523e06'
down_revision: Union[str, Sequence[str], None] = 'ee415be68cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_list_item_quoted', sa.Column('original_item_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'material_list_item_quoted', 'material_list_item', ['original_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'material_list_item_quoted', type_='foreignkey')
    op.drop_column('material_list_item_quoted', 'original_item_id')
    # ### end Alembic commands ###
