"""Add supplier_id to MaterialListItemQuoted

Revision ID: ee415be68cd3
Revises: cbac99a94c4d
Create Date: 2025-08-12 18:33:05.060671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee415be68cd3'
down_revision: Union[str, Sequence[str], None] = 'cbac99a94c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_list_item_quoted', sa.Column('supplier_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'material_list_item_quoted', 'user', ['supplier_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'material_list_item_quoted', type_='foreignkey')
    op.drop_column('material_list_item_quoted', 'supplier_id')
    # ### end Alembic commands ###
