import { z } from "zod"

export const materialsSchema = z.object({
    id: z.number(),
    item: z.string(),
    description: z.string(),
    unit: z.string(),
    quantity: z.number(),
    category: z.string(),
    subcategory: z.string(),
    metricQuantity: z.number(),
    updatedQuantity: z.number(),
    finalUnit: z.string(),
    status: z.string(),
})

export type Material = z.infer<typeof materialsSchema>

export const sampleMaterialsData: Material[] = [
    {
        id: 1,
        item: "Cemento",
        description: "Cemento Portland normal bolsa 50kg",
        unit: "kg",
        quantity: 180,
        category: "MAMPOSTERÍA Y TABIQUERÍA",
        subcategory: "Muros portantes",
        metricQuantity: 20,
        updatedQuantity: 24.5,
        finalUnit: "m2",
        status: "Presupuestado",
    },
    {
        id: 2,
        item: "Ladrillo común",
        description: "Ladrillo común de mampostería",
        unit: "u",
        quantity: 1000,
        category: "MAMPOSTERÍA Y TABIQUERÍA",
        subcategory: "Muros portantes",
        metricQuantity: 20,
        updatedQuantity: 20,
        finalUnit: "m2",
        status: "Presupuestado",
    },
    {
        id: 3,
        item: "Hierro ADN420",
        description: "Hierro para estructura",
        unit: "kg",
        quantity: 640,
        category: "MAMPOSTERÍA Y TABIQUERÍA",
        subcategory: "Muros portantes",
        metricQuantity: 20,
        updatedQuantity: 20,
        finalUnit: "m2",
        status: "Presupuestado",
    },
    {
        id: 4,
        item: "Arena fina",
        description: "Arena fina para mortero",
        unit: "m3",
        quantity: 5,
        category: "MAMPOSTERÍA Y TABIQUERÍA",
        subcategory: "Muros portantes",
        metricQuantity: 20,
        updatedQuantity: 18.5,
        finalUnit: "m2",
        status: "En proceso",
    },
    {
        id: 5,
        item: "Piedra partida",
        description: "Piedra partida 6-20mm",
        unit: "m3",
        quantity: 8,
        category: "HORMIGÓN ARMADO",
        subcategory: "Fundaciones",
        metricQuantity: 15,
        updatedQuantity: 15,
        finalUnit: "m3",
        status: "Pendiente",
    },
]
